{
  "hash": "ca02ad35e72986f4db49fe91cabe7aa8",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\nauthor: \"Geethika Tiramdas\"\nsubtitle: \"Assignment solutions\"\ntoc: true\nnumber-sections: false\n---\n\n\n## Part 1\n\nExample from previous chapter (parking spots) and draw the DAG.\n\nIn this DAG:\n\n* Location is the treatment variable (whether the store is in the city center or outside the city).\n* ParkingSpots is the variable representing whether the store has parking spots or not.\n* Sales is the outcome variable (sales of the store).\n\nThe arrows in the DAG indicate the causal relationships between the variables. For example, there is an arrow from Location to ParkingSpots indicating that the location influences the availability of parking spots.\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_be04233fc7a87291f2fb0b01012a289d'}\n\n```{.r .cell-code}\n# Load necessary packages\nlibrary(dagitty)\nlibrary(ggdag)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n#> ✔ dplyr     1.1.4     ✔ readr     2.1.4\n#> ✔ forcats   1.0.0     ✔ stringr   1.5.1\n#> ✔ ggplot2   3.4.4     ✔ tibble    3.2.1\n#> ✔ lubridate 1.9.3     ✔ tidyr     1.3.0\n#> ✔ purrr     1.0.2     \n#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n#> ✖ dplyr::filter() masks ggdag::filter(), stats::filter()\n#> ✖ dplyr::lag()    masks stats::lag()\n#> ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\n# Part 1 \ndag <- dagitty(\"dag {\n  ParkingSpots -> Sales\n  Location -> ParkingSpots\n  Location -> Sales\n}\")\n\nplot(dag)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Plot coordinates for graph not supplied! Generating coordinates, see ?coordinates for how to set your own.\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Draw DAG\nggdag(dag)\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n:::\n\n\n## Part 2\n\nUsing `lm` function as linear regression model. `summary` to display detailed information about regression models.\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_50a3ced3a61c3c217bca669b76a18061'}\n\n```{.r .cell-code}\ncust_sat <- readRDS(\"../../Causal_Data_Science_Data/customer_sat.rds\")\n\n# 1. regress satisfaction on follow_ups\nmodel1 <- lm(satisfaction ~ follow_ups, data = cust_sat)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = cust_sat)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n\n```{.r .cell-code}\n# 2. regress satisfaction on follow_ups and account for subscription\nmodel2 <- lm(satisfaction ~ follow_ups + subscription, data = cust_sat)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = cust_sat)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\n\n## Part 3\n\nBy observing both models, the coefficient for `follow_ups` is *-3.3093* in model 1, and *2.1944* in model 2.\n\nThis maybe interpreted as for model 1, for each additional follow up call, `satisfaction` is decreasing by 3.3093 units holding subscription constant. Whereas for model 2, `satisfaction` increases 2.1944 units holding subscription constant.\n\nBy comparison the relation between satisfaction and follow up maybe influenced by subscription, i.e., presence of subscription levels (Premium and Premium+) has an additional impact on satisfaction beyond the effect of follow-up calls alone.\n\n## Part 4\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_70d86b7607fea66d030e6b7433081536'}\n\n```{.r .cell-code}\n# Not conditioning on subscription\ncustomer_sat_not_cond <- ggplot(cust_sat, aes(x = follow_ups, y = satisfaction)) +\n  geom_point() +\n  stat_smooth(method = \"lm\", se = FALSE)\n\n# Conditioning on subscription\ncustomer_sat_cond <- ggplot(cust_sat, aes(x = follow_ups, y = satisfaction, color = subscription)) +\n  geom_point() +\n  stat_smooth(method = \"lm\", se = FALSE) +\n  theme(legend.position = \"right\")\n\n# Plot both\ncustomer_sat_not_cond\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncustomer_sat_cond\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}